### ISSUE TITLE
build error with ros environment

### ISSUE THREAD

**Issue by nhafez** [graspit-simulator/graspit_interface#35]
The graspit simulator was cloned and set up as a ros package. The command 

> rosrun graspit graspit_simulator

runs successully. I cloned the graspit interface package and when I tried to build it. I get the following error:

> In file included from /home/robocup17/Nawal_Projekt/build/graspit_interface/include/moc_graspit_interface.cxx:9:0:
/home/robocup17/Nawal_Projekt/build/graspit_interface/include/../../../src/graspit_interface/include/graspit_interface.h:11:28: fatal error: graspit/plugin.h: No such file or directory
compilation terminated.
In file included from /home/robocup17/Nawal_Projekt/src/graspit_interface/src/main.cpp:1:0:
/home/robocup17/Nawal_Projekt/src/graspit_interface/include/graspit_interface.h:11:28: fatal error: graspit/plugin.h: No such file or directory
compilation terminated.
graspit_interface/CMakeFiles/graspit_interface.dir/build.make:115: recipe for target 'graspit_interface/CMakeFiles/graspit_interface.dir/include/moc_graspit_interface.cxx.o' failed
make[2]: *** [graspit_interface/CMakeFiles/graspit_interface.dir/include/moc_graspit_interface.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
graspit_interface/CMakeFiles/graspit_interface.dir/build.make:91: recipe for target 'graspit_interface/CMakeFiles/graspit_interface.dir/src/main.cpp.o' failed
make[2]: *** [graspit_interface/CMakeFiles/graspit_interface.dir/src/main.cpp.o] Error 1

Your help is appreciated.

**Comment by jvarley** [comment]
I am assuming you followed the graspit setup here:
https://github.com/graspit-simulator/graspit-ros
It is deprecated. Honestly, that whole repo should just be deleted. 

Follow the instructions here instead:
https://github.com/graspit-simulator/graspit_interface

**Comment by nhafez** [comment]
I did follow these instructions. I got the build to work when I cloned https://github.com/CRLab/graspit_interface.git instead of git clone https://github.com/graspit-simulator/graspit_interface.git.

**Comment by jvarley** [comment]
@iretiayo  
why are you cloning the one from CRLab?

You should never be running;
rosrun graspit graspit_simulator

That comes from the deprecated setup.

**Comment by jvarley** [comment]
@iretiayo

**Comment by nhafez** [comment]
it was the one referenced [here](http://graspit-simulator.github.io/build/html/installation_ros.html)

**Comment by jvarley** [comment]
Ah, that documentation is out of date. Follow the instructions here:
https://github.com/graspit-simulator/graspit_interface

**Comment by nhafez** [comment]
These instructions result in the error mentioned above

**Comment by jvarley** [comment]
1) remove graspit-ros from your ros workspace.
2) install graspit the way it is install here: https://github.com/graspit-simulator/graspit_interface 
3) rebuild your ros workspce.

**Comment by nhafez** [comment]
yes, that worked. I had to delete the devel and build files as well. 
Thank you!
