### ISSUE TITLE
cmake error could not find Qhull

### ISSUE THREAD

**Issue by bentren** [graspit-simulator/graspit_interface#36]
I'm running into a problem with cmake during setup. I'm not a programmer, so am probably doing something dumb ... on a fresh install of Ubuntu 16.04.5. Any tips?

@ubuntu:~/graspit/build$ cmake ..
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Qhull (missing: QHULL_LIBRARY QHULL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  CMakeMacros/FindQhull.cmake:84 (find_package_handle_standard_args)
  CMakeLists.txt:71 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by jvarley** [comment]
Make sure you installed the depedencies:
https://graspit-simulator.github.io/build/html/installation_linux.html

**Comment by bentren** [comment]
Thank you! Installed dependencies and increased memory allocation from 1GB to 4GB and installation completed.
